apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b8zroynwr-python 
  janus-idp.io/tekton: b8zroynwr-python
  backstage.io/kubernetes-id: b8zroynwr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b8zroynwr-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml